global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  
  - job_name: 'iam-service'
    static_configs:
      - targets: ['iam-service:8081']
  
  - job_name: 'risk-assessment'
    static_configs:
      - targets: ['risk-assessment:8082']
  
  - job_name: 'news-aggregator'
    static_configs:
      - targets: ['news-aggregator:8083']
